env:
  browser: true
  es2021: true
extends:
  - airbnb-base
  - airbnb-typescript/base
parser: '@typescript-eslint/parser'
parserOptions:
  project: ./tsconfig.eslint.json
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
rules: 
  import/prefer-default-export: off
  max-len: 
    - error
    - code: 120
  semi: off
  '@typescript-eslint/semi':
    - error
    - never
